---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      description: User ID
      required: true
      schema:
        type: string
    - name: post_id
      in: path
      description: Post ID
      required: true
      schema:
        type: string
    get:
      summary: Shows comments in user's post
      tags:
      - Comments
      responses:
        '201':
          description: User post found
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment_id:
                    type: integer
                  author_id:
                    type: integer
                  post_id:
                    type: integer
                  text:
                    type: string
                required:
                - 'author_id:'
                - post_id
                - text
    post:
      summary: Create comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: Comment created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/v1/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: Shows posts from user
      tags:
      - Posts
      responses:
        '201':
          description: User posts found
          content:
            application/json:
              schema:
                type: object
                properties:
                  post_id:
                    type: integer
                  author_id:
                    type: integer
                  title:
                    type: string
                  text:
                    type: string
                required:
                - post_id
                - title
                - text
  "/api/v1/users":
    parameters:
    - name: Authorization
      in: header
      description: Authorization Token
      schema:
        type: string
    get:
      summary: Shows users
      tags:
      - User
      responses:
        '201':
          description: Users list
  "/api/v1/users/{user_id}":
    parameters:
    - name: Authorization
      in: header
      description: Authorization Token
      schema:
        type: string
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: Shows user info
      tags:
      - User
      responses:
        '201':
          description: User found
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  name:
                    type: string
                required:
                - user_id
                - name
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
